name: App build
on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get dfx
        run: |
          sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"

      - name: Build project
        run: |
          dfx build --check

      - name: Get didc
        run: |
          release=$(curl --silent "https://api.github.com/repos/dfinity/candid/releases/latest" | grep -e '"tag_name"' | cut -c 16-25)  	
          curl -fsSL https://github.com/dfinity/candid/releases/download/${release}/didc-linux64 > ~/bin/didc

      - name: Check .did files
        run: |
          ~/bin/didc check .dfx/local/canisters/ledger/ledger.did src/ledger/ledger.did   
          ~/bin/didc check .dfx/local/canisters/aggregator/aggregator.did src/aggregator/aggregator.did   
