name: App build
on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

env:
  vessel_version: v0.6.4
  moc_version: 0.7.0
  dfx_version: 0.12.0-beta.2
  ic-repl_version: 0.3.4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-22.05

      - name: "Install wasmtime"
        run: |
          nix-env --install wasmtime --file '<nixpkgs>'
  
      - name: Make bin directory
        run: mkdir -p /home/runner/bin

      - name: "install Motoko binaries"
        run: |
          wget https://github.com/dfinity/motoko/releases/download/${{ env.moc_version }}/motoko-linux64-${{ env.moc_version }}.tar.gz
          tar -xzf motoko-linux64-${{ env.moc_version }}.tar.gz -C /home/runner/bin
          echo "/home/runner/bin" >> $GITHUB_PATH

      - name: "install vessel"
        run: |
          wget --output-document /home/runner/bin/vessel https://github.com/kritzcreek/vessel/releases/download/${{ env.vessel_version }}/vessel-linux64
          chmod +x /home/runner/bin/vessel

      - name: "test"
        run: make -C test

      - name: Get dfx
        run: |
          DFX_VERSION=${{ env.dfx_version }} sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"

      - name: Build project
        working-directory: ./test
        run: |
          dfx build --check

      - name: Get didc
        run: |
          release=$(curl --silent "https://api.github.com/repos/dfinity/candid/releases/latest" | grep -e '"tag_name"' | cut -c 16-25)  	
          curl -fsSL https://github.com/dfinity/candid/releases/download/2022-08-09/didc-linux64 > /home/runner/bin/didc
          chmod +x /home/runner/bin/didc

      - name: Check .did files
        working-directory: ./test
        run: |
          /home/runner/bin/didc check .dfx/local/canisters/ledger/ledger.did ../src/ledger/ledger.did   
          /home/runner/bin/didc check .dfx/local/canisters/agg0/agg0.did ../src/aggregator/aggregator.did   

      - name: Install ic-repl
        run: |
          wget https://github.com/chenyan2002/ic-repl/releases/download/${{ env.ic-repl_version }}/ic-repl-linux64
          mv ./ic-repl-linux64 /home/runner/bin/ic-repl 
          chmod a+x /home/runner/bin/ic-repl

      - name: Start local dfx
        working-directory: ./test
        run: |
          dfx start --host 127.0.0.1:4943 --background

      - name: Run ledger load test
        working-directory: ./test
        run: |
          rm -f ./performance_tests/cycle_stats.txt
          ic-repl ./performance_tests/test_ledger.sh

      - name: Run aggregator load test
        working-directory: ./test
        run: |
          ic-repl ./performance_tests/test_aggregator.sh

      - name: update stats
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: '*_stats.txt'
          commit_message: '[skip ci] update stats'
          push_options: --force

      - name: Stop local dfx
        working-directory: ./test
        run: |
          dfx stop
